# Site settings
#
# Date of this Update to Config-template file ver 02-05-2018
#
# Uncomment theme for docs folder
theme: "jekyll-theme-cayman"
#
# There is one main repository as of 12-31-17
# repository: https://www.github.com/MMINAIL/mminail.github.io
#
# There are approx sixty auxillary repositories as of 12-31-17
# repository: https://www.github.com/rwebaz/Markdown-Lessons-Project
#
title: "Markdown Lessons Project"
lang: "en-US"
tagline: "A GitHub repo of Lessons and Articles that emphasize both the GFM and Kramdown development languages"
description: "The Markdown Lessons Project, or MLP is a GitHub repo of Lessons and Articles emphasizing both the GFM and Kramdown development languages."
twitter:
    username: "mminail"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github_username: "rwebaz"
    twitter_username: "rwebaz"
# The 'baseurl' is the subpath of your designated project, e.g. /Blank-Lessons-Project or /blog or simply "/"
baseurl: "/Markdown-Lessons-Project"
# The 'url' is the parental web address of your designated project, e.g. /https://mminail.github.io
url: "https://rwebaz.github.io"
exclude: ['README.md']
markdown: "kramdown"
highlighter: "rouge"
kramdown:
    input: "GFM"
    hard_wrap: "false"
    syntax_highlighter: "rouge"
    math_engine: "mathjax"
timezone: "America/Phoenix"
google_analytics: [UA-44765001-15]
# Settings For Default Keys: Use a scope/values pair
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/png"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/img/svg"
    values:
      image: "true"
defaults:
  - scope:
      path: "assets/ico"
    values:
      image: "true"
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      category: "markdown"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      category: "markdown"
excerpt_separator: <!-- this is a literal excerpt separator -->
collections:
  gists:
    output: "true"
defaults:
  - scope:
      path: "_gists"
      type: "pages"
    values:
      category: "markdown"
plugins_dir:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Gemfile.old
